name: app
description: "All4Sport AP4"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  auto_height_grid_view: ^1.0.0
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  go_router: ^13.2.0
  http: ^1.2.0
  intl: ^0.19.0
  qr_code_dart_scan: ^0.7.5
  qr_scanner_overlay: ^0.0.2
  provider: ^6.1.2
  sliding_clipped_nav_bar: ^3.1.0+4
  url_launcher: ^6.2.5
  geolocator: ^11.0.0
  geocoding: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
